//
// Created by cowerling on 17-4-25.
//

#ifndef CREST_STATUSRESULT_H
#define CREST_STATUSRESULT_H

enum StatusResultType {
    RUNOFF, EVAPORATION, SOIL_WATER, SURFACE_EXCESS, GROUND_EXCESS, SURFACE_RESERVOIR, GROUND_RESERVOIR
};

#endif //CREST_STATUSRESULT_H
